[project]
name = "resonatehq.io.code"
version = "0.1.0"
description = "Resonate Async RPC example application"
authors = [
    { name = "Resonate HQ", email = "contact@resoantehq.io" }
]
dependencies = [
    "flask>=3.1.0",
    "resonate-sdk>=0.6.1"
]

readme = "README.md"
requires-python = ">=3.12"
